Repository ogame-infinity/web-extension, pull requests merged in 2023-08, with the labels that each got.

#213 fix the minute to remove leading 0
  packaging.sh
Labels: bug

#214 improve storage display for big number
  .eslintrc.js
  global.css
  ogkush.js
Labels: improvements

#212 Refactor/fleet messages
  global.css
  ogkush.js
Labels: improvements

#217 add the localization on fleet message
  ogkush.js
Labels: improvements

#219 Update prettier and eslint versions
  .eslintrc.js
  ogkush.js
  package-lock.json
  package.json
  readme.md
Labels: documentation
